version: '3'
services:
  web:
    image: docker-akka-http:0.0.1
    volumes:
      - ./src/main/webapp/assets:/app/webapp
    environment:
        JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - "8080:8080"
      - "5005:5005"