version: '3'
services:
  web:
    image: edwinjwood/docker-akka-http:latest<skipPull>
    volumes:
      - ./src/main/webapp/assets:/app/webapp
    environment:
        JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - "8888:8888"
      - "5005:5005"